# Place this file next to the streama-[version].war and rename to application.yml with your own settings
environments:
  production:
    dataSource:
      driverClassName:  'org.h2.Driver'
      url: jdbc:h2:./streama;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
      username: root
      password:
    server: 94.72.104.115
      port: 8080
streama:
  regex:
    movies:
      - ^(?<Name>.*)[._ ]\(\d{4}\).*
      - ^(?<Name>.*)[._ ].*

    shows:
      - ^(?<Name>.+)[._ ][Ss](?<Season>\d{2})[Ee](?<Episode>\d{2,3}).*    # example:  "House.MD.S03E04.h264.mp4"
      - ^(?<Name>.+)[._ ](?<Season>\d{1,2})x(?<Episode>\d{2,3}).*         # example:  "House.MD.03x04.h264.mp4"
      - ^(?<Season>\d{2})-(?<Episode>\d{2,3})-(?<Name>.*?)-.*             # example:  "02-05-Dr. House-Tanz_ums_Feuer-cineonws.mp4"
      - ^(?<Name>.*?)(?<Episode>\d{1,3})x(?<Season>\d{2}).*               # example:  "Castle4x06DaemonsWebdl480pOktober242011rC.mkv(jkuzt).mp4"

grails:
  mail:
    host: "smtp.gmail.com"
    port: 465
    username: "noahalarcon.ma@gmail.com"
    # If you have enabled the two-step verification, create an app specific password.
    # If you have not enabled the two-step verification, turn on "Allow less secure apps" option.
    password: "orka13560"
    props:
      mail.smtp.auth: "true"
      mail.smtp.socketFactory.port: "465"
      mail.smtp.socketFactory.class: "javax.net.ssl.SSLSocketFactory"
      mail.smtp.socketFactory.fallback: "false"
